-----------------------------------------
-- 1. Currencies table (Valyuta cedveli)
-----------------------------------------

CREATE TABLE currencies (
    currency_code CHAR(3), -- AZN, USD, EUR
    currency_name VARCHAR2(50) NOT NULL,
    exchange_rate NUMBER(10,4) DEFAULT 1 NOT NULL, -- [EN] AZN ratio | [AZ] AZN-e nisbet
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_currency PRIMARY KEY (currency_code)
);

INSERT INTO currencies (currency_code, currency_name, exchange_rate) VALUES ('AZN', 'Azerbaijani Manat', 1);
INSERT INTO currencies (currency_code, currency_name, exchange_rate) VALUES ('USD', 'US Dollar', 1.70);
INSERT INTO currencies (currency_code, currency_name, exchange_rate) VALUES ('EUR', 'Euro', 1.85);
COMMIT;


-------------------------------------------
-- 2. Customers table (Musteriler cedveli)
-------------------------------------------

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    fin_code CHAR(7) UNIQUE NOT NULL, -- FIN CODE
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20),
    status VARCHAR2(10) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);


----------------------------------------
-- 3. Accounts table (Hesablar cedveli)
----------------------------------------

CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    iban VARCHAR2(28) UNIQUE NOT NULL,
    currency_code CHAR(3) DEFAULT 'AZN',
    balance NUMBER(15,2) DEFAULT 0 NOT NULL,
    account_type VARCHAR2(10) CHECK (account_type IN ('CURRENT', 'SAVINGS')),
    status VARCHAR2(10) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'FROZEN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_account PRIMARY KEY (account_id),
    
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_account_currency FOREIGN KEY (currency_code) REFERENCES currencies(currency_code),
    CONSTRAINT chk_balance_positive CHECK (balance >= 0)
);


-------------------------------------------------
-- 4. Transactions table (Emeliyyatlar cedveli)
-------------------------------------------------

CREATE TABLE transactions (
    transaction_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    from_account_id     NUMBER, 
    to_account_id       NUMBER,   
    source_amount       NUMBER(15,2) NOT NULL,
    target_amount       NUMBER(15,2) NOT NULL,
    applied_rate        NUMBER(10,4) NOT NULL,
    transaction_type    VARCHAR2(20) CHECK (transaction_type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL')),
    description         VARCHAR2(200),
    transaction_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status              VARCHAR2(10) DEFAULT 'SUCCESS' CHECK (status IN ('SUCCESS', 'FAILED')),
    
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT fk_from_account FOREIGN KEY (from_account_id) REFERENCES accounts(account_id),
    CONSTRAINT fk_to_account FOREIGN KEY (to_account_id) REFERENCES accounts(account_id),
    CONSTRAINT chk_source_amount_gt_zero CHECK (source_amount > 0)
);


-----------------------------
-- 5. Audit log table
-----------------------------

CREATE TABLE account_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_id NUMBER,
    old_balance NUMBER(15,2),
    new_balance NUMBER(15,2),
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    db_user VARCHAR2(50), -- [AZ] Emeliyyatı eden DB istifadeci
    CONSTRAINT pk_log PRIMARY KEY (log_id)
);